import { getRunControl, runUsage, type RunControl } from "@sce/db";
import { cancellationBus, runBus } from "@sce/queue";
import { isTerminalRunStatus, type RunEvent } from "@sce/shared";
import { workerConfig } from "./env.ts";

/**
 * The per-job context every step of a run shares.
 *
 * Two things are threaded through it, and both used to be implicit:
 *
 *   - **the tenant**, carried explicitly so that every persistence call in this
 *     package is scoped by construction rather than by remembering;
 *   - **the stop conditions** — cancellation, the run deadline, the per-run
 *     budget — gathered into one object so a step cannot accidentally check two
 *     of the three.
 */

export interface RunContext {
  tenantId: string;
  runId: string;
  /** Persist (unless ephemeral) and publish one progress event. */
  emit(event: RunEvent): Promise<void>;
}

export function contextFor(tenantId: string, runId: string): RunContext {
  const bus = runBus();
  return {
    tenantId,
    runId,
    async emit(event: RunEvent): Promise<void> {
      await bus.publish(tenantId, runId, event);
    },
  };
}

/* ------------------------------------------------------------- stop checks */

/** Why a step should not proceed. `null` means it should. */
export type StopReason =
  | { kind: "canceled"; message: string }
  | { kind: "deadline"; message: string }
  | { kind: "budget"; message: string }
  | { kind: "finished"; message: string }
  | { kind: "missing"; message: string };

/**
 * Decide whether the next model call may happen.
 *
 * Every condition is read from the database rather than from worker memory,
 * because the fan-out is spread across processes: the candidate that pushed the
 * run over its token ceiling may have been generated by a different machine
 * thirty seconds ago. Memory cannot know that; the `UsageRecord` rows can.
 */
export async function checkStop(
  tenantId: string,
  runId: string,
  now: Date = new Date(),
): Promise<StopReason | null> {
  const control = await getRunControl(tenantId, runId);
  if (!control)
    return { kind: "missing", message: `Run ${runId} no longer exists` };

  if (control.canceledAt !== null) {
    return {
      kind: "canceled",
      message: control.cancelReason ?? "Run was canceled",
    };
  }
  if (isTerminalRunStatus(control.status)) {
    return {
      kind: "finished",
      message: `Run already finished as ${control.status}`,
    };
  }
  if (
    control.deadlineAt !== null &&
    control.deadlineAt.getTime() <= now.getTime()
  ) {
    return {
      kind: "deadline",
      message: `Run deadline of ${control.deadlineAt.toISOString()} passed before this step started`,
    };
  }

  return checkBudget(tenantId, runId, control);
}

/** The spend half of `checkStop`, split out so tests can drive it directly. */
export async function checkBudget(
  tenantId: string,
  runId: string,
  control: RunControl,
): Promise<StopReason | null> {
  const tokenCeiling =
    control.maxTotalTokens ?? workerConfig.RUN_MAX_TOTAL_TOKENS;
  const costCeiling =
    control.maxCostMicroCents ?? workerConfig.RUN_MAX_COST_MICRO_CENTS;
  if (tokenCeiling === 0 && costCeiling === 0) return null;

  const spent = await runUsage(tenantId, runId);

  if (tokenCeiling > 0 && spent.totalTokens >= tokenCeiling) {
    return {
      kind: "budget",
      message: `Run token ceiling reached (${spent.totalTokens} of ${tokenCeiling})`,
    };
  }
  if (costCeiling > 0 && spent.costMicroCents >= costCeiling) {
    return {
      kind: "budget",
      message: `Run cost ceiling reached (${spent.costMicroCents} of ${costCeiling} micro-cents)`,
    };
  }
  return null;
}

/* ---------------------------------------------------------------- signals */

/**
 * An `AbortSignal` that fires on a timeout, with a reason worth persisting.
 *
 * `AbortSignal.timeout` reports as a bare `AbortError`, which is
 * indistinguishable from a client disconnect once it has been written to a
 * candidate row. Naming the budget that elapsed is the difference between "the
 * call was aborted" and "the Claude call exceeded its 120s budget".
 */
export function timeoutSignal(
  ms: number,
  what: string,
): { signal: AbortSignal; clear(): void } {
  const controller = new AbortController();
  const timer = setTimeout(() => {
    controller.abort(
      new Error(`${what} exceeded ${Math.round(ms / 1000)}s budget`),
    );
  }, ms);
  return {
    signal: controller.signal,
    clear: () => {
      clearTimeout(timer);
    },
  };
}

/**
 * Combine signals, preserving whichever reason fired first.
 *
 * `AbortSignal.any` exists and does almost this, but drops the reason on some
 * runtimes — and the reason is the entire value of the timeout signal above.
 */
export function anySignal(signals: readonly AbortSignal[]): {
  signal: AbortSignal;
  clear(): void;
} {
  const controller = new AbortController();
  const listeners: (() => void)[] = [];

  for (const signal of signals) {
    if (signal.aborted) {
      controller.abort(signal.reason);
      break;
    }
    const onAbort = (): void => {
      controller.abort(signal.reason);
    };
    signal.addEventListener("abort", onAbort, { once: true });
    listeners.push(() => {
      signal.removeEventListener("abort", onAbort);
    });
  }

  return {
    signal: controller.signal,
    clear: () => {
      for (const remove of listeners) remove();
    },
  };
}

/**
 * A signal that aborts when this run is canceled.
 *
 * Subscribes to the fast-path pub/sub channel *and* re-reads the database once
 * at subscription time, closing the window where the cancellation was published
 * a moment before this watcher connected. Missing the message would otherwise
 * cost the caller a full model call they had already asked to stop paying for.
 */
export async function cancellationSignal(
  tenantId: string,
  runId: string,
): Promise<{ signal: AbortSignal; clear(): Promise<void> }> {
  const controller = new AbortController();
  const abort = (reason: string): void => {
    if (!controller.signal.aborted) controller.abort(new Error(reason));
  };

  const unsubscribe = await cancellationBus().watch(runId, (message) => {
    abort(message.reason || "Run was canceled");
  });

  const control = await getRunControl(tenantId, runId);
  if (control?.canceledAt) abort(control.cancelReason ?? "Run was canceled");

  return {
    signal: controller.signal,
    clear: async () => {
      unsubscribe();
    },
  };
}

/** Milliseconds left before the run's deadline, or null when it has none. */
export function remainingMs(
  control: RunControl,
  now: Date = new Date(),
): number | null {
  if (control.deadlineAt === null) return null;
  return control.deadlineAt.getTime() - now.getTime();
}
